In [1]:
import pandas as pd
vendas_df = pd.read_excel("Vendas.xlsx")
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [20]:
valor_unitario_acima700 = vendas_df[(vendas_df['Valor Unitário'] > 700) & (vendas_df['Quantidade'] > 4)]
display(valor_unitario_acima700)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
10,8,2019-01-02,Iguatemi Campinas,Terno Estampa,5,706,3530
485,340,2019-01-03,Palladium Shopping Curitiba,Terno Xadrez,5,709,3545
768,515,2019-01-04,Shopping Midway Mall,Terno Estampa,5,706,3530
1032,689,2019-01-05,Bourbon Shopping SP,Terno Xadrez,5,709,3545
2635,1742,2019-01-11,Palladium Shopping Curitiba,Terno Xadrez,5,709,3545
...,...,...,...,...,...,...,...
92395,63948,2019-11-25,Shopping União de Osasco,Terno Estampa,5,706,3530
93031,64414,2019-11-27,Bourbon Shopping SP,Terno Liso,5,720,3600
93069,64441,2019-11-28,Shopping União de Osasco,Terno Listrado,5,709,3545
93142,64490,2019-11-28,Ribeirão Shopping,Terno Estampa,5,706,3530
93746,64910,2019-11-30,Shopping Barra,Terno Linho,5,750,3750

In [23]:
display(vendas_df.columns)

Index(['Código Venda', 'Data', 'ID Loja', 'Produto', 'Quantidade',
       'Valor Unitário', 'Valor Final'],
      dtype='object')

In [25]:
vendas_df.dropna()

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [36]:
produtos_df = vendas_df.groupby("Produto")
soma_df = produtos_df.sum()
mais_vendidos_df = produtos_df.max()
display(soma_df)
display(mais_vendidos_df)

                  Código Venda  Quantidade  Valor Unitário  Valor Final
Produto
Bermuda               25770079        1692          116100       253800
Bermuda Estampa       24703185        1616          127257       273104
Bermuda Linho         28670449        1893          167115       369135
Bermuda Liso          25053304        1637          120262       257009
Bermuda Listrado      25576302        1675          129259       273025
...                        ...         ...             ...          ...
Tênis Estampa         25479194        1663          200704       425728
Tênis Linho           25535255        1713          232848       503622
Tênis Liso            26076935        1656          205086       440496
Tênis Listrado        25533339        1737          207766       455094
Tênis Xadrez          26118680        1661          205905       430199

[120 rows x 4 columns]

,Código Venda,Data,ID Loja,Quantidade,Valor Unitário,Valor Final
Produto,,,,,,
Bermuda,65010,2019-11-30,Shopping Vila Velha,5,150,750
Bermuda Estampa,64953,2019-11-30,Shopping Vila Velha,5,169,845
Bermuda Linho,64980,2019-11-30,Shopping Vila Velha,5,195,975
Bermuda Liso,65012,2019-11-30,Shopping Vila Velha,5,157,785
Bermuda Listrado,64919,2019-11-30,Shopping Vila Velha,5,163,815
...,...,...,...,...,...,...
Tênis Estampa,64694,2019-11-29,Shopping Vila Velha,5,256,1280
Tênis Linho,64961,2019-11-30,Shopping Vila Velha,5,294,1470
Tênis Liso,64836,2019-11-30,Shopping Vila Velha,5,266,1330
Tênis Listrado,64884,2019-11-30,Shopping Vila Velha,5,262,1310
Tênis Xadrez,64928,2019-11-30,Shopping Vila Velha,5,259,1295

In [44]:
vendas_df.sort_values(by="Valor Unitário")

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
66764,46168,2019-08-26,Shopping Ibirapuera,Meia,2,30,60
89431,61911,2019-11-15,Palladium Shopping Curitiba,Meia,2,30,60
43559,29986,2019-06-05,Bourbon Shopping SP,Meia,1,30,30
55964,38692,2019-07-19,Shopping Barra,Meia,2,30,60
25744,17777,2019-04-03,Palladium Shopping Curitiba,Meia,1,30,30
...,...,...,...,...,...,...,...
72407,50210,2019-09-15,Bourbon Shopping SP,Terno Linho,1,750,750
58426,40375,2019-07-28,Salvador Shopping,Terno Linho,1,750,750
44445,30628,2019-06-08,Rio Mar Recife,Terno Linho,5,750,3750
83859,58150,2019-10-26,Shopping Barra,Terno Linho,2,750,1500
22524,15541,2019-03-22,Shopping Morumbi,Terno Linho,2,750,1500

In [49]:
tabela_dinamica_df = vendas_df.pivot_table(index="ID Loja", columns="Data", values="Quantidade")
display(tabela_dinamica_df)

Data,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,2019-01-10,...,2019-11-21,2019-11-22,2019-11-23,2019-11-24,2019-11-25,2019-11-26,2019-11-27,2019-11-28,2019-11-29,2019-11-30
ID Loja,,,,,,,,,,,,,,,,,,,,,
Bourbon Shopping SP,NaN,3.000000,2.000000,1.500000,2.315789,2.000000,1.916667,2.428571,2.052632,2.437500,...,1.625000,1.894737,2.600000,2.222222,2.058824,2.117647,3.000000,1.666667,1.727273,3.125000
Center Shopping Uberlândia,NaN,2.625000,2.500000,1.750000,2.076923,2.266667,2.000000,2.500000,2.647059,2.000000,...,2.166667,1.750000,2.357143,2.565217,2.000000,2.437500,3.500000,2.000000,2.250000,2.583333
Iguatemi Campinas,NaN,2.125000,2.000000,1.647059,2.250000,2.400000,1.666667,2.600000,1.571429,2.000000,...,3.000000,2.200000,2.400000,1.375000,2.375000,1.714286,2.000000,2.000000,2.222222,1.500000
Iguatemi Esplanada,1.333333,2.200000,2.000000,2.368421,2.000000,2.000000,1.750000,2.000000,1.714286,NaN,...,2.111111,1.400000,2.388889,2.500000,2.333333,1.583333,2.444444,2.333333,1.933333,1.800000
Norte Shopping,NaN,2.133333,1.166667,1.727273,2.500000,2.450000,1.607143,1.416667,4.000000,2.187500,...,2.666667,1.857143,2.250000,1.818182,2.000000,1.882353,2.000000,1.400000,1.000000,1.818182
Novo Shopping Ribeirão Preto,NaN,1.846154,1.800000,2.428571,2.000000,2.900000,2.142857,1.916667,1.928571,2.400000,...,2.153846,2.000000,2.727273,1.842105,2.470588,1.666667,2.200000,2.000000,2.695652,2.250000
Palladium Shopping Curitiba,NaN,2.700000,3.000000,2.266667,2.250000,1.666667,1.454545,1.666667,2.200000,1.818182,...,2.238095,2.600000,1.727273,1.500000,2.363636,2.190476,2.500000,2.230769,2.375000,1.777778
Parque Dom Pedro Shopping,NaN,2.157895,2.882353,2.444444,3.333333,1.800000,1.750000,1.333333,2.687500,2.500000,...,3.000000,1.800000,2.000000,2.000000,1.666667,1.833333,2.090909,1.454545,1.714286,2.500000
Passei das Águas Shopping,NaN,1.600000,1.812500,2.666667,2.363636,2.000000,1.666667,1.928571,1.375000,1.000000,...,2.000000,1.833333,1.833333,2.300000,2.866667,2.500000,1.888889,2.000000,2.157895,2.285714
Ribeirão Shopping,NaN,2.700000,2.521739,1.636364,2.050000,2.187500,1.700000,1.900000,2.166667,1.818182,...,2.545455,2.444444,2.062500,2.392857,2.375000,1.500000,2.555556,2.083333,2.153846,2.083333
Rio Mar Recife,NaN,1.666667,1.714286,2.125000,2.000000,2.000000,1.937500,2.000000,2.307692,1.894737,...,2.200000,3.000000,1.857143,2.222222,1.833333,1.888889,1.583333,2.210526,2.318182,2.333333
Rio Mar Shopping Fortaleza,NaN,2.000000,2.153846,2.333333,2.444444,2.416667,2.500000,2.090909,1.809524,2.333333,...,2.428571,2.428571,1.666667,2.285714,1.285714,2.111111,2.000000,2.333333,2.000000,2.250000
Salvador Shopping,NaN,2.142857,3.000000,2.400000,2.500000,2.000000,2.166667,1.875000,2.388889,2.000000,...,2.235294,2.000000,2.052632,2.368421,2.583333,2.000000,1.923077,2.000000,2.200000,2.055556
Shopping Barra,NaN,2.222222,3.500000,1.812500,2.294118,1.666667,1.937500,1.800000,2.400000,2.100000,...,2.176471,1.600000,2.000000,2.562500,2.666667,1.571429,2.200000,1.900000,1.875000,2.666667
Shopping Center Interlagos,NaN,1.933333,1.142857,2.500000,3.000000,2.000000,2.000000,1.600000,2.272727,2.666667,...,1.571429,2.600000,1.928571,1.500000,2.777778,1.800000,2.294118,3.500000,1.428571,1.800000
Shopping Center Leste Aricanduva,NaN,2.153846,2.272727,2.142857,1.928571,2.117647,2.266667,1.875000,2.368421,2.500000,...,2.000000,2.166667,2.529412,3.333333,3.166667,1.888889,2.300000,1.785714,2.153846,1.888889
Shopping Eldorado,NaN,1.809524,1.666667,2.222222,2.266667,1.750000,2.500000,2.166667,2.666667,1.714286,...,2.461538,2.555556,2.800000,1.700000,1.333333,2.222222,2.454545,1.583333,2.666667,2.222222
Shopping Ibirapuera,NaN,2.181818,2.000000,1.846154,1.800000,2.941176,2.611111,2.625000,1.714286,1.888889,...,2.000000,2.800000,3.250000,2.428571,2.400000,1.000000,2.444444,2.500000,2.285714,2.000000
Shopping Iguatemi Fortaleza,NaN,3.000000,1.857143,2.250000,2.333333,2.250000,2.571429,2.000000,1.900000,2.428571,...,2.153846,2.076923,2.000000,1.333333,2.333333,2.375000,1.833333,2.600000,2.461538,2.500000
Shopping Midway Mall,NaN,2.066667,2.428571,2.285714,3.666667,1.666667,2.142857,2.000000,1.900000,2.153846,...,2.000000,1.000000,2.888889,1.818182,1.500000,2.250000,2.333333,2.000000,2.166667,1.571429
Shopping Morumbi,NaN,2.200000,2.000000,2.000000,2.263158,2.250000,1.333333,1.952381,2.111111,1.545455,...,2.222222,2.047619,2.555556,1.714286,1.500000,1.692308,2.083333,1.700000,2.333333,2.692308
Shopping Recife,NaN,1.866667,1.769231,1.250000,2.545455,1.769231,2.142857,2.000000,1.000000,1.928571,...,1.750000,2.750000,2.500000,2.200000,2.500000,2.916667,2.062500,2.714286,2.500000,2.625000
Shopping SP Market,NaN,3.000000,2.500000,2.500000,2.000000,2.190476,2.428571,2.272727,1.923077,2.285714,...,1.833333,1.888889,2.142857,2.428571,2.064516,2.375000,2.500000,2.333333,2.000000,1.500000
Shopping União de Osasco,NaN,2.090909,2.315789,2.230769,1.894737,2.083333,1.400000,2.388889,2.166667,2.200000,...,2.000000,2.000000,1.823529,2.500000,2.400000,3.750000,1.928571,2.437500,1.636364,2.666667
Shopping Vila Velha,NaN,1.909091,2.416667,1.888889,2.500000,1.916667,2.000000,1.900000,1.666667,1.555556,...,2.600000,2.235294,2.470588,1.636364,2.000000,2.500000,1.714286,2.555556,1.857143,2.352941